a  = input('digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaço? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('é alfabético? {}'.format(a.isalpha()))
print('Ele é alfanumérico? {}'.format(a.isalnum()))
print('São letras maiusculas? {}'.format(a.isupper()))
print('São letras minúsculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))